name = "RealPolyhedralHomotopy"
uuid = "0ea325ba-5c5f-496b-acec-8be67510f465"
authors = ["Kisun Lee <kisunl@clemson.edu>","Julia Lindberg <julia.lindberg@math.utexas.edu>","Jose Israel Rodriguez <jose@math.wisc.edu>"]
version = "1.1.1"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MixedSubdivisions = "291d046c-3347-11e9-1e74-c3d251d406c6"
PolynomialRoots = "3a141323-8675-5d76-9d11-e1df1406c778"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
HomotopyContinuation = "2.6.4"
PolynomialRoots = "1.0.0"
AbstractAlgebra = "0.26.0"
DynamicPolynomials = "0.3, 0.4"
MixedSubdivisions = "1"
Reexport = "1.2.2"
julia = "1.6"
